### ISSUE TITLE
Kaktree not opening with the kitty terminal

### ISSUE THREAD

**Issue by LogFlames** [andreyorst/kaktree#8] opened 2021-03-01 14:05 UTC
## Problem description
Kaktree doesn't open when using the kitty terminal emulator. From my testing I think the problem might be in kaktree--display, the variable $kak_opt_termcmd is empty, thus not running the shell command on line 192 in rc/kaktree.kak which should create a new buffer called \*kaktree\* and client.

## Steps to reproduce
1. Open kakoune (with kaktree installed) in kitty
2. Type :kaktree-toggle\<ret\>
3. Nothing happens

## What should happen
A new window containing the filetree should open.

## What happens instead
The first time :kaktree-toggle<ret> is run nothing happens, after the first time the command gives the error:
> Error: 1:1: 'kaktree-toggle' 1:2: 'evaluate-commands' 2:28: 'evaluate-commands' no such client 'kaktreeclient'

in the \*debug\* buffer.

## Environment information
Kakoune version: Kakoune v2020.09.01-339-g7c321e12
OS version: Manjaro Linux 20.2.1 Nibia
\`sh\` executable version: GNU bash, version 5.1.0(1)-release (x86_64-pc-linux-gnu)

**Comment by andreyorst** [comment] 2021-09-23 18:13
Hi, sorry for delay. Somehow notifications did not came at all. I don't use Kitty, and AFAIK it requires some configuration to manipulate splits, can you add a minimal config for kitty so I could debug against it?

**Comment by UltraBlackLinux** [comment] 2022-10-22 21:57
> can you add a minimal config for kitty so I could debug against it?

I think anything suffices if you just want a working config. Just install it.

**Comment by andreyorst** [comment] 2022-10-23 10:04
> I think anything suffices if you just want a working config. Just install it.

As far as I know, kitty by default doesn't allow any outside control of a terminal, i.e. creating splits, windows, etc. I don't know what user settings are present, what settings Kitty has in general, or what their protocol extensions are, and hence can't tell if the problem is in the plugin or in kitty's configuration.

> I am replying here, because the merged "fix" does not work, sadly

The mentioned fix is in another plugin.

In my case, when I open Kakoune in Kitty, there's no `termcmd` option set, hence Kaktree can't display anything. This is a Kakoune issue - it doesn't set `termcmd` for Kitty, not Kaktree. Stupidly enough, when I open Kakoune in GNOME Terminal, Kakoune sets the `termcmd` to `kitty` and Kaktree works and opens in the Kitty terminal. The terminal detection mechanism in Kakoune is busted IMO. 

Closing, as this is an upstream issue.

**Closed by andreyorst** 2022-10-23 10:04 UTC
Labels: bug
